server:
  port: 9003
  servlet:
    context-path: /file
spring:
  application:
    name: file
  datasource:
    username: root
    password: 1160576878
    url: jdbc:mysql://localhost:3306/course
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB